// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_terminal::schema::lib::TerminalName as TerminalName;
#[rustfmt::skip]
pub use signal_terminal::schema::lib::TerminalExitStatus as TerminalExitStatus;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalCommandExecutable(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalCommandArgument(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalEnvironmentName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalEnvironmentValue(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalWorkingDirectory(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WirePath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Name(TerminalName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Terminal(TerminalName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Executable(TerminalCommandExecutable);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Arguments(Vec<TerminalCommandArgument>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EnvironmentName(TerminalEnvironmentName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EnvironmentValue(TerminalEnvironmentValue);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Command(TerminalCommand);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Environment(Vec<TerminalEnvironmentBinding>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WorkingDirectory(Option<TerminalWorkingDirectory>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DataSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExitStatus(Option<TerminalExitStatus>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Operation(MetaTerminalOperationKind);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Reason(MetaTerminalUnimplementedReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalCommand {
    pub executable: Executable,
    pub arguments: Arguments,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TerminalEnvironmentBinding {
    pub environment_name: EnvironmentName,
    pub environment_value: EnvironmentValue,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CreateSession {
    pub name: Name,
    pub command: Command,
    pub environment: Environment,
    pub working_directory: WorkingDirectory,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireSession(Name);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SessionCreated {
    pub name: Name,
    pub data_socket_path: DataSocketPath,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SessionRetired {
    pub name: Name,
    pub exit_status: ExitStatus,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MetaTerminalOperationKind {
    CreateSession,
    RetireSession,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MetaTerminalUnimplementedReason {
    NotBuiltYet,
    DependencyTrackNotLanded,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MetaTerminalRequestUnimplemented {
    pub terminal: Terminal,
    pub operation: Operation,
    pub reason: Reason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    CreateSession(CreateSession),
    RetireSession(RetireSession),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SessionCreated(SessionCreated),
    SessionRetired(SessionRetired),
    MetaTerminalRequestUnimplemented(MetaTerminalRequestUnimplemented),
}

#[rustfmt::skip]
impl TerminalCommandExecutable {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TerminalCommandExecutable {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalCommandArgument {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TerminalCommandArgument {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalEnvironmentName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TerminalEnvironmentName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalEnvironmentValue {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TerminalEnvironmentValue {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TerminalWorkingDirectory {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TerminalWorkingDirectory {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WirePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WirePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Name {
    pub fn new(payload: TerminalName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalName {
        &self.0
    }
    pub fn into_payload(self) -> TerminalName {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalName> for Name {
    fn from(payload: TerminalName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Terminal {
    pub fn new(payload: TerminalName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalName {
        &self.0
    }
    pub fn into_payload(self) -> TerminalName {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalName> for Terminal {
    fn from(payload: TerminalName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Executable {
    pub fn new(payload: TerminalCommandExecutable) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalCommandExecutable {
        &self.0
    }
    pub fn into_payload(self) -> TerminalCommandExecutable {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalCommandExecutable> for Executable {
    fn from(payload: TerminalCommandExecutable) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Arguments {
    pub fn new(payload: Vec<TerminalCommandArgument>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<TerminalCommandArgument> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<TerminalCommandArgument> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<TerminalCommandArgument>> for Arguments {
    fn from(payload: Vec<TerminalCommandArgument>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EnvironmentName {
    pub fn new(payload: TerminalEnvironmentName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalEnvironmentName {
        &self.0
    }
    pub fn into_payload(self) -> TerminalEnvironmentName {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalEnvironmentName> for EnvironmentName {
    fn from(payload: TerminalEnvironmentName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EnvironmentValue {
    pub fn new(payload: TerminalEnvironmentValue) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalEnvironmentValue {
        &self.0
    }
    pub fn into_payload(self) -> TerminalEnvironmentValue {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalEnvironmentValue> for EnvironmentValue {
    fn from(payload: TerminalEnvironmentValue) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Command {
    pub fn new(payload: TerminalCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TerminalCommand {
        &self.0
    }
    pub fn into_payload(self) -> TerminalCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<TerminalCommand> for Command {
    fn from(payload: TerminalCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Environment {
    pub fn new(payload: Vec<TerminalEnvironmentBinding>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<TerminalEnvironmentBinding> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<TerminalEnvironmentBinding> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<TerminalEnvironmentBinding>> for Environment {
    fn from(payload: Vec<TerminalEnvironmentBinding>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WorkingDirectory {
    pub fn new(payload: Option<TerminalWorkingDirectory>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<TerminalWorkingDirectory> {
        &self.0
    }
    pub fn into_payload(self) -> Option<TerminalWorkingDirectory> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<TerminalWorkingDirectory>> for WorkingDirectory {
    fn from(payload: Option<TerminalWorkingDirectory>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DataSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for DataSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ExitStatus {
    pub fn new(payload: Option<TerminalExitStatus>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<TerminalExitStatus> {
        &self.0
    }
    pub fn into_payload(self) -> Option<TerminalExitStatus> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<TerminalExitStatus>> for ExitStatus {
    fn from(payload: Option<TerminalExitStatus>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Operation {
    pub fn new(payload: MetaTerminalOperationKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MetaTerminalOperationKind {
        &self.0
    }
    pub fn into_payload(self) -> MetaTerminalOperationKind {
        self.0
    }
}
#[rustfmt::skip]
impl From<MetaTerminalOperationKind> for Operation {
    fn from(payload: MetaTerminalOperationKind) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Reason {
    pub fn new(payload: MetaTerminalUnimplementedReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MetaTerminalUnimplementedReason {
        &self.0
    }
    pub fn into_payload(self) -> MetaTerminalUnimplementedReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<MetaTerminalUnimplementedReason> for Reason {
    fn from(payload: MetaTerminalUnimplementedReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetireSession {
    pub fn new(payload: Name) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Name {
        &self.0
    }
    pub fn into_payload(self) -> Name {
        self.0
    }
}
#[rustfmt::skip]
impl From<Name> for RetireSession {
    fn from(payload: Name) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn create_session(payload: CreateSession) -> Self {
        Self::CreateSession(payload)
    }
    pub fn retire_session(payload: Name) -> Self {
        Self::RetireSession(RetireSession::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn session_created(payload: SessionCreated) -> Self {
        Self::SessionCreated(payload)
    }
    pub fn session_retired(payload: SessionRetired) -> Self {
        Self::SessionRetired(payload)
    }
    pub fn meta_terminal_request_unimplemented(
        payload: MetaTerminalRequestUnimplemented,
    ) -> Self {
        Self::MetaTerminalRequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<CreateSession> for Input {
    fn from(payload: CreateSession) -> Self {
        Self::CreateSession(payload)
    }
}

#[rustfmt::skip]
impl From<RetireSession> for Input {
    fn from(payload: RetireSession) -> Self {
        Self::RetireSession(payload)
    }
}

#[rustfmt::skip]
impl From<SessionCreated> for Output {
    fn from(payload: SessionCreated) -> Self {
        Self::SessionCreated(payload)
    }
}

#[rustfmt::skip]
impl From<SessionRetired> for Output {
    fn from(payload: SessionRetired) -> Self {
        Self::SessionRetired(payload)
    }
}

#[rustfmt::skip]
impl From<MetaTerminalRequestUnimplemented> for Output {
    fn from(payload: MetaTerminalRequestUnimplemented) -> Self {
        Self::MetaTerminalRequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_CREATE_SESSION: u64 = 0x0000000000000000;
    pub const INPUT_RETIRE_SESSION: u64 = 0x0001000000000000;
    pub const OUTPUT_SESSION_CREATED: u64 = 0x0100000000000000;
    pub const OUTPUT_SESSION_RETIRED: u64 = 0x0101000000000000;
    pub const OUTPUT_META_TERMINAL_REQUEST_UNIMPLEMENTED: u64 = 0x0102000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    CreateSession,
    RetireSession,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    SessionCreated,
    SessionRetired,
    MetaTerminalRequestUnimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::CreateSession(_) => InputRoute::CreateSession,
            Self::RetireSession(_) => InputRoute::RetireSession,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::CreateSession(_) => short_header::INPUT_CREATE_SESSION,
            Self::RetireSession(_) => short_header::INPUT_RETIRE_SESSION,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_CREATE_SESSION => Ok(InputRoute::CreateSession),
            short_header::INPUT_RETIRE_SESSION => Ok(InputRoute::RetireSession),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::SessionCreated(_) => OutputRoute::SessionCreated,
            Self::SessionRetired(_) => OutputRoute::SessionRetired,
            Self::MetaTerminalRequestUnimplemented(_) => {
                OutputRoute::MetaTerminalRequestUnimplemented
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::SessionCreated(_) => short_header::OUTPUT_SESSION_CREATED,
            Self::SessionRetired(_) => short_header::OUTPUT_SESSION_RETIRED,
            Self::MetaTerminalRequestUnimplemented(_) => {
                short_header::OUTPUT_META_TERMINAL_REQUEST_UNIMPLEMENTED
            }
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_SESSION_CREATED => Ok(OutputRoute::SessionCreated),
            short_header::OUTPUT_SESSION_RETIRED => Ok(OutputRoute::SessionRetired),
            short_header::OUTPUT_META_TERMINAL_REQUEST_UNIMPLEMENTED => {
                Ok(OutputRoute::MetaTerminalRequestUnimplemented)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &["CreateSession", "RetireSession"];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
